# Generated by Django 2.0.1 on 2018-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitjang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_time', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_data', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_text',
            field=models.TextField(default=''),
        ),
    ]
