# Generated by Django 2.0.1 on 2018-02-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitjang', '0003_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
