# Generated by Django 2.0.1 on 2018-03-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitjang', '0005_auto_20180311_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='mets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
