# Generated by Django 2.0.1 on 2018-03-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitjang', '0006_activity_mets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='mets',
            new_name='calories',
        ),
    ]
