# Generated by Django 2.0.1 on 2018-03-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitjang', '0007_auto_20180311_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='calories',
            field=models.FloatField(default=0),
        ),
    ]
